"""Added players table

Revision ID: 1eb2c79a34bc
Revises: 
Create Date: 2025-11-21 11:38:29.176433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1eb2c79a34bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('place_of_birth', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('place_of_birth_title', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('place_of_birth_flag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('foot', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('citizenship', sa.JSON(), nullable=True),
    sa.Column('citizenship_flag', sa.JSON(), nullable=True),
    sa.Column('headshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('club', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('club_logo', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('main_position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('other_positions', sa.JSON(), nullable=True),
    sa.Column('national_team', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('national_team_flag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('caps', sa.Integer(), nullable=True),
    sa.Column('international_goals', sa.Integer(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('league_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('league_level', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('league_logo', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('joined_date', sa.Date(), nullable=True),
    sa.Column('contract_expires', sa.Date(), nullable=True),
    sa.Column('agency_info', sa.JSON(), nullable=True),
    sa.Column('club_stats', sa.JSON(), nullable=True),
    sa.Column('national_team_stats', sa.JSON(), nullable=True),
    sa.Column('current_season_stats', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
